### ISSUE TITLE
Only one secret is nicely decoded.

### ISSUE THREAD

**Issue by nmiculinic** [lbolla/kube-secret-editor#1]
I have 3 secrets in the file, a, b, c. All three are json files. However upon using this tool, only the first one, a, is nicely decoded with |+.

Other two are ugly, with \r\n thrown around etc.

**Comment by lbolla** [comment]
Can you please provide me with an example?

I tried the following.

Generate some json files:

```
In [6]: json.dump({i: 'x' * i for i in range(100)}, open('/tmp/issue1/a.json', 'w'))
In [7]: json.dump({i: 'x' * i for i in range(100)}, open('/tmp/issue1/b.json', 'w'))
In [8]: json.dump({i: 'x' * i for i in range(100)}, open('/tmp/issue1/c.json', 'w'))
```

Create a secret:

`kubectl create secret generic --from-file=/tmp/issue1 issue1`

Edit it and it looks good to me.

**Comment by nmiculinic** [comment]
Hmm now it works. I cannot replicate anymore.
